### PR TITLE
Icons+Fix

### PR DESCRIPTION
**Pull request by Pageot**

### CODE REVIEW

**Comment by Pageot** [comment]
Hey Pierre, I want to merge my branch into master, you can check my code ?

**Comment by SunSemillia** [comment]
You have an error, check the file page.scss (around line 65)

**Comment by Pageot** [comment]
Oh yes, I didn't see, I fix it.
After that, I merge, everything is ok ?

**Comment by SunSemillia** [comment]
Ok it's good, you can merge it !

**Comment by Pageot** [comment]
It's done, thank you !  🙂👌

**Pull request merged**
